openapi: 3.1.0
info:
  title: todo
  summary: Service in charge of managing todo notes
  description: |6-

        This service records todo notes, the following api calls are available:

        * adding a todo notes
        * listing/finding todo notes
        * getting the details of a todo note
        
  version: MISSING VERSION
paths:
  /todo/{id}:
    get:
      summary: Get the content of a todo note
      description: |8-

                Returns the content of a particular todo notes as a string.
                
      operationId: todo.get
  /todo:
    post:
      summary: Adds a todo note
      description: |8-

                Will add a todo note through providing its content.
                
      operationId: todo.add
    get:
      summary: Find todo notes
      description: |8-

                Lists todo notes matching a query string passed as the only argument.
                
      operationId: todo.find
